version: "3"
services:
  postgres:
    image: postgres:16
    container_name: tts-postgres
    expose:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - movies-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5