"""initial_migration

Revision ID: 1ea2152d1a49
Revises: 
Create Date: 2025-07-18 09:01:12.460419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea2152d1a49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('country_name_en', sa.Enum('Russia', 'Germany', 'Portugal', name='countryen'), nullable=False),
    sa.Column('country_name_ru', sa.Enum('Россия', 'Германия', 'Португалия', name='countryru'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_name_en'),
    sa.UniqueConstraint('country_name_ru'),
    schema='audio_guide'
    )
    op.create_table('cities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('city_name_en', sa.Enum('Moscow', 'Lisbon', 'Ludwigsburg', name='cityen'), nullable=False),
    sa.Column('city_name_ru', sa.Enum('Москва', 'Лиссабон', 'Людвигсбург', name='cityru'), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['audio_guide.countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name_en'),
    sa.UniqueConstraint('city_name_ru'),
    schema='audio_guide'
    )
    op.create_table('landmarks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('landmark_name_en', sa.String(), nullable=False),
    sa.Column('landmark_name_ru', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['audio_guide.cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'landmark_name_en'),
    schema='audio_guide'
    )
    op.create_table('descriptions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('landmark_id', sa.Uuid(), nullable=False),
    sa.Column('desc_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['audio_guide.landmarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc_path'),
    schema='audio_guide'
    )
    op.create_table('images',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('landmark_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['audio_guide.landmarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path'),
    schema='audio_guide'
    )
    op.create_table('audios',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('landmark_id', sa.Uuid(), nullable=False),
    sa.Column('desc_id', sa.Uuid(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.SmallInteger(), nullable=False),
    sa.Column('language', sa.String(length=2), server_default='ru', nullable=False),
    sa.Column('voice_gender', sa.String(length=6), server_default='male', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['desc_id'], ['audio_guide.descriptions.id'], ),
    sa.ForeignKeyConstraint(['landmark_id'], ['audio_guide.landmarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_path'),
    sa.UniqueConstraint('desc_id'),
    schema='audio_guide'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries', schema='audio_guide')
    op.drop_table('cities', schema='audio_guide')
    op.drop_table('landmarks', schema='audio_guide')
    op.drop_table('descriptions', schema='audio_guide')
    op.drop_table('images', schema='audio_guide')
    op.drop_table('audios', schema='audio_guide')

    op.execute('DROP TYPE IF EXISTS countryen')
    op.execute('DROP TYPE IF EXISTS countryru')
    op.execute('DROP TYPE IF EXISTS cityen')
    op.execute('DROP TYPE IF EXISTS cityru')
    # ### end Alembic commands ###
