"""add_lat_long

Revision ID: 2a79a4855c41
Revises: 7db135d18765
Create Date: 2025-05-11 12:57:16.169105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a79a4855c41'
down_revision: Union[str, None] = '7db135d18765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placeofinterest', sa.Column('lat', sa.Float()))
    op.add_column('placeofinterest', sa.Column('long', sa.Float()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placeofinterest', 'long')
    op.drop_column('placeofinterest', 'lat')
    # ### end Alembic commands ###
