"""audio_add_lang_gender_columns

Revision ID: 57c05046f313
Revises: f6644d135343
Create Date: 2025-05-07 21:36:46.569776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c05046f313'
down_revision: Union[str, None] = 'f6644d135343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('lang', sa.String(), server_default='ru', nullable=False))
    op.add_column('audio', sa.Column('gender', sa.String(), server_default='male', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio', 'gender')
    op.drop_column('audio', 'lang')
    # ### end Alembic commands ###
