"""initial

Revision ID: 93f7a0c93f17
Revises: 
Create Date: 2025-04-09 20:14:15.779645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f7a0c93f17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('placeofinterest',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('city_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('description',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('place_of_interest_id', sa.String(length=128), nullable=False),
    sa.Column('desc_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_of_interest_id'], ['placeofinterest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc_path')
    )
    op.create_table('image',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('place_of_interest_id', sa.String(length=128), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_of_interest_id'], ['placeofinterest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path')
    )
    op.create_table('audio',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('description_id', sa.String(length=128), nullable=False),
    sa.Column('place_of_interest_id', sa.String(length=128), nullable=False),
    sa.Column('audio_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['description.id'], ),
    sa.ForeignKeyConstraint(['place_of_interest_id'], ['placeofinterest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_path'),
    sa.UniqueConstraint('description_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio')
    op.drop_table('image')
    op.drop_table('description')
    op.drop_table('placeofinterest')
    op.drop_table('city')
    # ### end Alembic commands ###
