"""delete_durationsec_colum_from_audios

Revision ID: d51668557f4d
Revises: 237a5be0ccfc
Create Date: 2025-07-23 13:26:28.732020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51668557f4d'
down_revision: Union[str, None] = '237a5be0ccfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audios', 'duration_sec', schema='guide')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('duration_sec', sa.SMALLINT(), autoincrement=False, nullable=False), schema='guide')
    # ### end Alembic commands ###
